package com.gatex.entity;

public enum ImageType {
    FACE_FRONT,
    FACE_LEFT,
    FACE_RIGHT,
    FACE_SLIGHT_LEFT,
    FACE_SLIGHT_RIGHT,
    FACE_UPDOWN,
    UNIFORM_GOOD,
    UNIFORM_BAD,
    UNIFORM_BAD_MISSING_TIE,
    UNIFORM_BAD_MISSING_BELT,
    UNIFORM_BAD_MISSING_ID_CARD
}
